### ISSUE TITLE
[BUG] Function tests against AOS endpoint with security didn't work

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/opensearch-dashboards-functional-test#100]
**What is the bug?**
Function tests against AOS endpoint (not localhost) with security didn't work, the failure screenshot stuck at login pages.

**How can one reproduce the bug?**
Run the function tests as following command sample:
`env TZ=America/Los_Angeles npx cypress run --browser chrome --headless --env SECURITY_ENABLED=true,openSearchUrl=https://url,username={username},password={password} --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js' --config "baseUrl=https://url/_dashboards"`

**What is the expected behavior?**
The test should all pass, but all the tests failed as stuck at login pages.

**What is your host/environment?**
 - OS: IOS
 - Version: 12.2.1
 - Plugins

**Do you have any screenshots?**
The failure screenshot stuck at login page

**Do you have any additional context?**
None

**Comment by Tengda-He** [comment]
where is the url parameter defined? it should be the domain endpoint

**Comment by Tengda-He** [comment]
did some test, you need to add this "ENDPOINT_WITH_PROXY=true" to env in the cli, to make it work

**Comment by tianleh** [comment]
Thank @Tengda-He for researching this! @Flyingliuhub could you help verify?

**Comment by Flyingliuhub** [comment]
Thanks Tengda.

Two behaviors:
1. cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js works with config overrides of username & password & proxy
2. cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/*.js doesn't work with config overrides of username & password & proxy


If we are planning to use opensearch-dashboards tests, we should update CONTRIBUTING paging and not pointing to vanilla-opensearch-dashboards
