### ISSUE TITLE
[BUG] Visualization Builder Tests failed

### ISSUE THREAD

**Issue by raintygao** [opensearch-project/opensearch-dashboards-functional-test#1082]
### What is the bug?
Some test cases of Visualization Builder failed.

![image](https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/42465692/9216ed25-3bc9-4534-9788-6102de053512)
core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js: Be able to add/ edit and remove a field https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7637122802/job/20954769803

![image](https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/42465692/1c568eac-fff9-4652-943a-0741aa75cb40)

core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js:  https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7637122802/job/20805372311#step:15:1057

**Comment by raintygao** [comment]
Hi @ashwin-pc , could you take a look on vis builder failed test cases above? These issues are related to some DOM issues, my team tried to fix them, but not sure if they're due to some feature and design updates or bugs, can you fix them?

**Comment by kavilla** [comment]
Will close, i dont think we are seeing this issue anymore. For the release I believe another plugin was using the same class names and !important the styles so it messed up the visbuilder and caused issues. But that has been addressed.

If not please re-open and we will look into them but we are kind of looking at them all already.
