### ISSUE TITLE
[FEATURE] Remove push event triggers in all workflow

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/opensearch-dashboards-functional-test#1108]
### Is your feature request related to a problem?
The push triggered flow fails to launch as it requests `checkout` action first before doing `path-filter`.

### What solution would you like?
Remove the useless push event as all the commit happens with a pull request, we do not allow contributors to push to a branch directly.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7938831230/job/21678772804?pr=1107

**Comment by wanglam** [comment]
@SuZhou-Joe Will the pull request events re-run after new commits pushed?

**Comment by Hailong-am** [comment]
pull event might be useful for fork repos to test changes. Also @ruanyl have a PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1017 to solve similar issue.

**Comment by SuZhou-Joe** [comment]
> pull event might be useful for fork repos to test changes. Also @ruanyl have a PR #1017 to solve similar issue.

I see, didn't know that.
