### ISSUE TITLE
[BUG] Github action not run for security-dashboard-plugin

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/opensearch-dashboards-functional-test#1139]
### What is the bug?
Github action not run for security-dashboard-plugin folder

https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/security-release-e2e-workflow.yml#L16

the path should include both
 `- 'cypress/**/security-dashboards-plugin/**'`
 `- 'cypress/**/security/**'`

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by ruanyl** [comment]
Is this issue resolved?

**Comment by Hailong-am** [comment]
> Is this issue resolved?

yes, close it now
