### ISSUE TITLE
[BUG] Test cases of multiple data source feature are failing

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/opensearch-dashboards-functional-test#1198]
### What is the bug?
Test cases of multiple data source feature are failing due to multiple reasons
See [cypress-test-log.txt](https://github.com/opensearch-project/opensearch-dashboards-functional-test/files/14831645/cypress-test-log.txt) for report of test

- one failure example caused by switching from `EuiSelect` to `EuiSuperSelect` in data source logic code in OSD repo.
```
CypressError: `cy.select()` can only be called on a `<select>`. Your subject is a: `<button type="button" class="euiSuperSelectControl" aria-haspopup="true" aria-labelledby="ie6187031-f0a7-11ee-9f0b-c7c5328dde65 ie6d75361-f0a7-11ee-9f0b-c7c5328dde65" data-test-subj="createDataSourceFormAuthTypeSelect">Usernam...</button>`
```

### How can one reproduce the bug?
1. enable datasource from `cypress.json` by setting `"DATASOURCE_MANAGEMENT_ENABLED": true,`
3. Run cypress tests cases for datasource management plugin and observe the results or check the screenshots and videos
```
yarn cypress run --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/*.js"
```
### What is the expected behavior?
tests should pass

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/32652829/bb27da8c-b00e-45f6-9262-51ba64c62f9e)

cc: @seraphjiang

**Comment by zhongnansu** [comment]
I am happy to work on this

**Comment by kavilla** [comment]
@zhongnansu hey Zhongnan! How's it going!

Sounds good go for it!
