### ISSUE TITLE
[BUG] Address skipped failing tests in Observability

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/opensearch-dashboards-functional-test#121]
**What is the bug?**
Currently there are some flaky tests in Observability's cypress tests. On most runs they will succeed but a few of them will fail. Need to dive deep and address the root cause to fix the test suite permanently. 

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by tianleh** [comment]
@davidcui1225 Any plan to move forward?

**Comment by ps48** [comment]
This doesn't have any context on which observability test is failing. We are currently working on all component test updates for observability. Closing this issue for now.

**Comment by ps48** [comment]
@wanglam Can you please help close this issue!

**Comment by wanglam** [comment]
Confirmed with @ps48 , this issue doesn't related specific test case. Since they are working on all component test updates,  close this issue for now.
