### ISSUE TITLE
[FEATURE] Functional tests for workspace create and update page

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/opensearch-dashboards-functional-test#1220]
### Is your feature request related to a problem?
No

### What solution would you like?
Add functional tests for workspace create and update page

### Do you have any additional context?
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6179
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6270

**Comment by kavilla** [comment]
Seems to be closed by 1221. Will close. @gaobinlong if closed in error please re-open. Thank you!
