### ISSUE TITLE
Add documentation about building from source for Cypress on arm64 linux

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#137]
Cypress has no official support for arm64 on linux. We have to build from source for this. This issue is to detail the steps.

**Comment by peterzhuamazon** [comment]
We can create a dockerfile with scripts on it.
This is better than manually mcm this.

**Comment by tianleh** [comment]
Link to the dockerfile https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile

**Comment by tianleh** [comment]
Opensearch dockers https://hub.docker.com/r/opensearchstaging/ci-runner/tags

**Comment by peterzhuamazon** [comment]
Close this as we already record the steps in the dockerfile.
