### ISSUE TITLE
Get AD tests to consistently pass in Cypress 9.x

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-dashboards-functional-test#147]
There's an ongoing campaign to upgrade cypress to 9.5.2 (#136). One consistent failure is seen when running AD tests (see [comment](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/144#issuecomment-1076965731)). Investigate this separately

**Comment by tianleh** [comment]
This is one recent example of failure of "detector_list_spec.js" in 5.6.1 https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5669009345?check_suite_focus=true

You can find more examples here https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/126#issuecomment-1068353477
