### ISSUE TITLE
[PROPOSAL] Check if env variable and build spec from it

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-dashboards-functional-test#153]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/integtest.sh#L82

^ This file is used by the build repo to trigger integration tests for OpenSearch Dashboards. How about we we default to the `TEST_FILES` to be all test files but we check an environment variable to see there exists a $TEST_FILES environment variable already set. When this file is executed it will be executing from the CI in a docker container. 

If we request the CI test runner image to include the ability to see the `TEST_FILES` as an environment variable we can utilize [this](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-dashboards-2.0.0-test.yml#L5) and pass `args: TEST_FILES='cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js,'` or (or we do the work of adding `cypress/integration`). So that when the docker container runs and executes the tests there the integtest.sh script will check if this variable is there see and set the TEST_FILES variable to the value passed from the test manifest.

Cons:
* Messy test manifest?
* Multi-repo knowledge, but really any can then set an environment variable locally and execute the tests they want.

Pros:
* Plugins don't have to create a commit here every time they add their plugin to the manifest
* Gives us granular control on what tests are being executed. Specifically I wish I had a better way of retesting specific tests that have failed without creating my own fork, branch, modifying the script to ensure I execute the test I want, update the build manifest in the build repo, retrigger the build of OSD so that it can get the right commit (the commit with my changes) for the FTRepo and then that point I have my tests I can hit in the CI environment. But with this proposal all I need to do when retrying tests is just ensure my test manifest has the right variables. We could further expand the build repo test jenkinsfile to accept an input of string that we can add a csv list of test files that it can add as an environment variable.

**Comment by tianleh** [comment]
Close this since the related PR has been merged.
