### ISSUE TITLE
Bump github actions to use stable 2.0 build once ready

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-dashboards-functional-test#189]
Github actions using workflow to download  an artifact but currently uses 1.3. Some tests are not compatible with 1.3 on the main branch. But we don't really have a stable build for 2.0 yet. So once we do we should switch the github actions on main to use 2.0 or refactor it to pull the package version.

**Comment by tianleh** [comment]
For every plugin workflow, update the version. 

See this sample location
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/alerting-release-e2e-workflow.yml#L13

**Comment by tianleh** [comment]
If https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/142 is done, this issue will need to just read `package.json`
