### ISSUE TITLE
Use Prettier to automate formatting and fixing JavaScript

### ISSUE THREAD

**Issue by CCongWang** [opensearch-project/opensearch-dashboards-functional-test#195]
Prettier was added in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/70, contributors need to run `npx prettier * --write` manually to auto format and fix existing files. We plan to integrate prettier with eslint in https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/186 to improve code quality, but there will be a lot of code change based on prettier rules since we haven't ran `npx prettier * --write` for a while. 
Therefore, we plan to run `npx prettier * --write` in this issue to fix all style issues based on prettier rules, then we will integrate prettier with eslint in https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/186 to make the PR easier to review.

**Comment by seraphjiang** [comment]
should we need to list all folder/components we plan to breakdown and run
e.g.
- [ ] plugins\security
- [ ] core
- [ ] ...

**Comment by CCongWang** [comment]
@seraphjiang I was thinking that running `npx prettier * --write` for all files should be sufficient, but I guess you are right, I can run for each folder in each commit, so it will be easier for plugin owners to review the changes

**Comment by seraphjiang** [comment]
not sure how much chance, if only a few files, `npx prettier * --write` works :)
this is great step to improve code quality leveraging automation script

**Comment by CCongWang** [comment]
I have ran `npx prettier {path} --write` against each folder to fix styling issued based on prettier rules, please find affected plugins below:
- [ ] alerting plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/a505bc05c432a1050d20fb7611f8c265e063d190)
- [ ] AD plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/8a44cf113a7d37ad4d574da6f7928a9587ae9108)
- [ ] security plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/e470a5024d170d1db4111eea13841cb51593b626)
- [ ] observability plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/488d7b8bc637ac7821ba525d2dc718dd1d7098b8)
- [ ] query workbench plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/95cae321215b7e2f5f4e540fed7333d27ec5c748)
- [ ] report plugin, see [commit](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/196/commits/82cb13b18233f4c4d804cb63074602af35992893)

I will check and make sure tests pass.

**Comment by CCongWang** [comment]
[3 tests from observability failed](https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6164496902?check_suite_focus=true):
* plugins/observability-dashboards/5_event_analytics.spec.js
  * `Redirect to correct page on breadcrumb click:
     AssertionError: Timed out retrying: Expected to find content: 'Explorer' within the element: <span.euiBreadcrumb.euiBreadcrumb--last> but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js:110:30)`
* plugins/observability-dashboards/7_app_analytics.spec.js
  * `Opens service detail flyout when Service Name is clicked:
     AssertionError: Timed out retrying: Expected to find element: `.euiFlyout`, but never found it.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js:378:26)
`
  * `Opens trace detail flyout when Trace ID is clicked:
     AssertionError: Timed out retrying: Expected to find element: `.euiFlyout`, but never found it.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js:399:26)
` 

I have checked my code changes, they shouldn't cause the 3 tests failing, I wonder if the tests are just flaky recently or there is something wrong with prettier fix?
@kavilla do you see those test failing recently?
@davidcui1225 could you please take a look?
Thank y'all!

**Comment by kavilla** [comment]
> [3 tests from observability failed](https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/6164496902?check_suite_focus=true):
> 
> * plugins/observability-dashboards/5_event_analytics.spec.js
>   
>   * `Redirect to correct page on breadcrumb click: AssertionError: Timed out retrying: Expected to find content: 'Explorer' within the element: <span.euiBreadcrumb.euiBreadcrumb--last> but never did. at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js:110:30)`
> * plugins/observability-dashboards/7_app_analytics.spec.js
>   
>   * `Opens service detail flyout when Service Name is clicked: AssertionError: Timed out retrying: Expected to find element: `.euiFlyout`, but never found it. at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js:378:26) `
>   * `Opens trace detail flyout when Trace ID is clicked: AssertionError: Timed out retrying: Expected to find element: `.euiFlyout`, but never found it. at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js:399:26) `
> 
> I have checked my code changes, they shouldn't cause the 3 tests failing, I wonder if the tests are just flaky recently or there is something wrong with prettier fix? @kavilla do you see those test failing recently? @davidcui1225 could you please take a look? Thank y'all!

Yeah that's fine. I can reject again but observability side is good but I wouldn't be against another verification from the Observability plugin
