### ISSUE TITLE
[PROPOSAL] Enforcing coding conventions and formatting with Husky pre-commit hooks

### ISSUE THREAD

**Issue by CCongWang** [opensearch-project/opensearch-dashboards-functional-test#198]
**What is the problem? What is preventing you from meeting the requirements?**
`prettier` was added in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/70, and was integrated with `ESLint` to apply coding conventions and formatting rules to the project in https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/186. However, contributors need to manually run the lint command to lint and fix the code, if we don't run them regularly, we see inconsistent code formatting around the project.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
We can utilize [Husky pre-commit hooks](https://typicode.github.io/husky/#/) to run lint command and formatting check automatically, to make sure code changes in each commit are consistent in coding conventions and formatting.

**Comment by seraphjiang** [comment]
add small request, could we add the pre-commit setup/usage to
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md

**Comment by CCongWang** [comment]
@joshuali925 @ohltyler @davidcui1225 @bowenlan-amzn @annie3431 

Hi plugin owners, we plan to use precommit hook to run lint command automatically, the goal is to make the code styles and formatting consistent, please check out [the PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/201) and updated `Formatting` section in CONTRIBUTING. Let me know if you have questions/concerns/suggestions! Thanks!
