### ISSUE TITLE
Trigger only related plugin tests on PR check when one particular plugin folder is changed

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#211]
Currently all action workflows will run even if the PR changes an individual folder. We want to achieve the following goal, e.g if AD test has a change, only AD workflow will run on PR check

**Comment by tianleh** [comment]
@peterzhuamazon

**Comment by peterzhuamazon** [comment]
There are existing actions for us to achieve this:
https://github.com/dorny/paths-filter

I will write a test case soon.

**Comment by peterzhuamazon** [comment]
Resolved in #213.
