### ISSUE TITLE
Backport tests to OSD 1.0 and 1.1

### ISSUE THREAD

**Issue by CCongWang** [opensearch-project/opensearch-dashboards-functional-test#218]
Branch 1.0 and 1.1 are currently missing, we will need to create branches and backport tests.

**Comment by CCongWang** [comment]
My plan is:
1. create a new branch called 1.0 off branch 1.2, `git checkout 1.2; git checkout -b 1.0`, push the new branch 1.0
2. make necessary change in 1.0, like changing the version and fixing the tests, create a PR
3. do the same for 1.1

@seraphjiang @tianleh @kavilla Let me know if you have any questions or suggestions, thanks!

**Comment by tianleh** [comment]
> My plan is:
> 
>     1. create a new branch called 1.0 off branch 1.2, `git checkout 1.2; git checkout -b 1.0`, push the new branch 1.0
> 
>     2. make necessary change in 1.0, like changing the version and fixing the tests, create a PR
> 
>     3. do the same for 1.1
> 
> 
> @seraphjiang @tianleh @kavilla Let me know if you have any questions or suggestions, thanks!

Looks good! Thanks for the backporting!

**Comment by CCongWang** [comment]
closed since both https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/226 and https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/225 have been merged.
