### ISSUE TITLE
Investigate flaky test in security dashboards functional test

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-dashboards-functional-test#280]
During the latest functional test build for version 2.2, a test in permissions_spec.js: "should create new action group successfully by selecting `Create from blank`" intermittently fails during cy.intercept() call in `mockPermissions` in [command.js](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/63978b6597918056f9a5cd22427eaaf14a869996/cypress/utils/plugins/security/commands.js#L61)

Failure artifact:
[security.zip](https://github.com/opensearch-project/security-dashboards-plugin/files/9329327/security.zip)

**Comment by Hailong-am** [comment]
looks like fix by https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/284 and https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/561

**Comment by Hailong-am** [comment]
confirmed with @RyanL1997 this not happened after release 2.7, we can close it for now. 
We can re-open if we surface it again in future release.
