### ISSUE TITLE
Release version 2.3.0

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-dashboards-functional-test#285]
This is a component issue for __2.3.0__.
Coming from [opensearch-build#2447](https://github.com/opensearch-project/opensearch-build/issues/2447). Please follow the following checklist.
__Please refer to the DATES in that post__.

<details><summary>How to use this issue</summary>
<p>

## This Component Release Issue

This issue captures the state of the OpenSearch release, on component/plugin level; its assignee is responsible for driving the release. Please contact them or @mention them on this issue for help. 
Any release related work can be linked to this issue or added as comments to create visiblity into the release status.

## Release Steps

There are several steps to the release process; these steps are completed as the whole component release and components that are behind present risk to the release. The component owner resolves the tasks in this issue and communicate with the overall release owner to make sure each component are moving along as expected.

Steps have completion dates for coordinating efforts between the components of a release; components can start as soon as they are ready far in advance of a future release. The most current set of dates is on the overall release issue linked at the top of this issue.

## The Overall Release Issue

Linked at the top of this issue, the overall release issue captures the state of the entire OpenSearch release including references to this issue, the release owner which is the assignee is responsible for communicating the release status broadly.  Please contact them or @mention them on that issue for help.

## What should I do if my plugin isn't making any changes?

If including changes in this release, increment the version on __2.x__ branch to __2.3.0__ for Min/Core, and __2.3.0.0__ for components. Otherwise, keep the version number unchanged for both.

</p>
</details>

### Preparation [Done] 

- [x] Assign this issue to a release owner.
- [x] All the tasks in this issue have been reviewed by the release owner.
- [x] Create, update, triage and label all features and issues targeted for this release with `v2.3.0`.
- [x] All code changes for `2.3.0` are complete.
- [x] Create branch 2.3

### Pre-Release [Done]
- [x] #288
- [x] #286
- [x] Confirm that all changes for `2.3.0` have been merged.

### During Release Testing

- [x] Review any PRs in this repo during the release

### Release

- [x] Complete [documentation] if there's any changes (https://github.com/opensearch-project/documentation-website).
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) for the next developer iteration. (2.4.0) 
- [ ] Add this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/) of the next eventual security patch version. (2.3.1)
- [x] Prepare for an eventual security fix development iteration by incrementing the version on the release branch to the next eventual patch version.
- [x] [Suggest improvements](https://github.com/opensearch-project/opensearch-build/issues/new) to [this template](https://github.com/opensearch-project/opensearch-build/blob/main/meta/templates/releases/release_template.md).
- [x] Conduct a retrospective, and publish its results.
  - [ ] https://github.com/opensearch-project/opensearch-build/issues/2671 
- [ ] #305

**Comment by tianleh** [comment]
Are we able to close this issue? @noCharger

**Comment by noCharger** [comment]
> Are we able to close this issue? @noCharger 

Will double check the post release items and close it today
