### ISSUE TITLE
Remove Observability flaky tests from FTR

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/opensearch-dashboards-functional-test#289]
### Is your feature request related to a problem?
Some of the tests/test suits for Observability plugin are flaky which causes false alarms for releases from time to time.

### What solution would you like?
Remove unnecessary but prone-to-be-flaky tests, and fix/improve those that are necessary.

**Comment by tianleh** [comment]
@mengweieric Do you have an ETA for this task?

**Comment by mengweieric** [comment]
> @mengweieric Do you have an ETA for this task?

Yes, it's in the roadmap of 2.4 releases.

**Comment by tianleh** [comment]
Can I assign the issue to you or another teammate will take care of this?

**Comment by mengweieric** [comment]
Please assign to me thanks.

**Comment by wanglam** [comment]
Confirmed with @mengweieric , the related fix has been merged. This issue can be closed.
