### ISSUE TITLE
Integrate with OpenSearch Build/CI process. Test run could be triggered and ran by CI

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#3]

**Comment by seraphjiang** [comment]
could this task break down to small ones

**Comment by tianleh** [comment]
Task is being tracked inside infra's build repo https://github.com/opensearch-project/opensearch-build/issues/604

**Comment by tianleh** [comment]
Already run after every distribution build from infra
