### ISSUE TITLE
[PROPOSAL] - Enable automation of release notes generation

### ISSUE THREAD

**Issue by ZilongX** [opensearch-project/opensearch-dashboards-functional-test#346]
### What are you proposing?

Enable automation of release notes generation.

### What users have asked for this feature?

Developer / Customer to get better understanding of the release items

### What problems are you trying to solve?

Generate release note automatically instead of manually

### What is the developer experience going to be?

Developer won't need to manually update the release notes.

#### Are there any security considerations? 

Not for now, this would a native functionality provided directly from github https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

#### Are there any breaking changes to the API

NO

**Comment by seraphjiang** [comment]
rest api for integration
https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release

**Comment by seraphjiang** [comment]
how this feature being developed
https://github.com/community/community/discussions/5962
