### ISSUE TITLE
[Feature Anywhere] Support test to validate rendering line charts with vega-lite

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/opensearch-dashboards-functional-test#425]
### Is your feature request related to a problem?
There is a new change where the line chart will be able to be rendered through vega-lite from this issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2915.

### What solution would you like?
Once there is more work done [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2882), there will be a and proper end to end integration to test annotations being displayed on line charts using vega-lite

**Comment by ohltyler** [comment]
Will consider this a duplicate of #430 which encapsulates all validation of the charts
