### ISSUE TITLE
Modify Cypress version to match infra Docker image

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#44]

**Comment by tianleh** [comment]
check if Cypress `5.6.0` is working

**Comment by Tengda-He** [comment]
attached test pass video.
https://user-images.githubusercontent.com/89666799/144489827-e7ef2633-b3cb-4728-8f74-5387bb18b149.mp4

**Comment by tianleh** [comment]
After Tengda's change, I verified that it can work inside infra.
