### ISSUE TITLE
[RFC] Add release version support

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#45]
**Is your feature request related to a problem? Please describe.**
As more Dashboards plugin teams onboard release tests on this repo, we notice that there could be some test case changes caused by the UI functional changes between versions. E.g `1.3.0` may add a new page and thus related tests which do not apply at all in `1.2.0`. Currently this repo only has a single `main` branch to capture the latest test cases. Thus we may need a mechanism to manage the versioned test cases if we want to run regression of past versions.

**Describe the solution you'd like**
I am proposing using the version branch in this repo. (Similar to https://github.com/opensearch-project/OpenSearch-Dashboards)
Create minor branches (e.g 1.0, 1.2) and also 1.x for next 1.3 releases. Once 1.3 is ready for release, create a tag 1.3.0 Then use main branch for next 2.x releases. This will need some cherry picks of commits from main branch to 1.x branch development.

**Describe alternatives you've considered**

**Option A:**
Once a new release say `1.5.0` kicks off (assume the previous release is `1.4.0`), I will update the `package.json` of this repo to `1.5.0`. Only the plugin teams need to add new test cases (or modify old test cases) have to send pull requests for those changes. When `1.5.0` release is over, I will create a new branch named `1.5.0` based on `main` branch. Also I will update the corresponding branch in build manifest in build repo. (E.g https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0/opensearch-dashboards-1.2.0.yml#L16)

For current `main` branch which is written for `1.2.0`, I will just create a `1.2.0` branch based on `main` as a backfill.

The drawback of this approach is that we may need some prefix to the branch name to avoid conflict with tag. Also another branch is needed for managing next major changes.

**Option B:**
Another approach I considered is using folders where each folder corresponding to a version. The benefit is that there is no branch versioning in this repo. The drawbacks are

1) The code for different versions is duplicated in the same branch. (even though under different directories.)
2) Make this repo an outlier in build manifest https://github.com/opensearch-project/opensearch-build/blob/29dd05fc30f35f1143986d39d2852890b1c109ae/manifests/1.2.0/opensearch-dashboards-1.2.0.yml#L16
3) based on 2) and will require special logic to use a directory of this repo instead of checking out the branch in build repo https://github.com/opensearch-project/opensearch-build/blob/29dd05fc30f35f1143986d39d2852890b1c109ae/src/run_checkout.py#L33

**Additional context**
A recent example from AD plugin team https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/95#issuecomment-1056021422

~~Currently this repo only has one release branch `main`. Once there are different UI behaviors in different OSD versions, we will need to add version support for this repo as well.~~

**Comment by tianleh** [comment]
For now, we will only track latest version in `main` branch, no version specific branch.

**Comment by tianleh** [comment]
@ohltyler Feel free to share expectations from Dashboards plugin team's perspective.

**Comment by ohltyler** [comment]
As a plugin owner, I would expect to be able to run a version of my plugin, and run the corresponding tests for the plugin that are compatible with that specific version.

I think following the same versioning and release strategy as the rest of the OpenSearch core and plugins would be a good solution for this.

**Comment by tianleh** [comment]
Please help review this RFC @dblock @zengyan-amazon @sichend @seraphjiang @kavilla @tmarkley @seanneumann

**Comment by kavilla** [comment]
I agree @ohltyler, it can follow the same versioning strategy. As core and the plugins, that being we create branches for `1.3` and once we are prepared to release create a tag for `1.3.0`

**Comment by tianleh** [comment]
@peterzhuamazon

**Comment by tianleh** [comment]
> I agree @ohltyler, it can follow the same versioning strategy. As core and the plugins, that being we create branches for `1.3` and once we are prepared to release create a tag for `1.3.0`. With main being the latest and greatest and supporting breaking changes. We also create a `1.x` with a version bump targeting `1.next`

Thanks for the input! Updated my proposal to use this one as proposed.

**Comment by tmarkley** [comment]
Agreed! Syncing on the versioning strategy is the ideal approach I think.

**Comment by tianleh** [comment]
All related branches have been created and will continue to operate in such a way
