### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-dashboards-functional-test#546]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch Dashboards Functional Test repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch Dashboards Functional Test | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Link Checker, Lint, Bundled Tests, tests added from other repositories | https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/546 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by ashwin-pc** [comment]
The BWC tests for OSD reside in the OSD repo itself. @kavilla Should we move them here so that we dont have to have a complicated test structure?

**Comment by scrawfor99** [comment]
Hi @ashwin-pc and @kavilla, thank you for following up. I will update the notes to show your change. Let me know if there is anything else I should address.

**Comment by seraphjiang** [comment]
this repo is not plugin repo, not applicable to the policy. in the future if we create repo like load-testing, it should be excluded as well.

thanks @scrawfor99 for check, and thanks @ashwin-pc and @kavilla for triage. closing the issue.
