### ISSUE TITLE
Tests for search-relevance-dashboards  failed due to sample data exists

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#577]
During the 2.6.0, team noticed that sample data already exists when the page was visited and thus failed to see the button to add sample data.

See the video
https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.6.0/5520/linux/x64/tar/test-results/3169/integ-test/functionalTestDashboards/without-security/test-results/cypress-videos/plugins/search-relevance-dashboards/1_query_compare.spec.js.mp4

Below is the link to all plugins.
https://opensearch-project.github.io/opensearch-dashboards-functional-test/site/?version=2.6.0&build_number=5520&test_number=3169

We need to verify whether other tests are adding sample data but didn't clean up.

**Comment by tianleh** [comment]
Find suspicious tests in observability. Sample data was added but not removed.

https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/observability-dashboards/0_before.spec.js#L21

https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/observability-dashboards/8_after.spec.js#L9

@joshuali925 Could you please take a look?

**Comment by joshuali925** [comment]
@tianleh should `cy.deleteAllIndices();` https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/5e601cc1a4fa9be79c75fa39db4086d6ac8def4a/cypress/utils/commands.js#L99-L106 also delete `.kibana_*`?

**Comment by tianleh** [comment]
> @tianleh should `cy.deleteAllIndices();`
> 
> https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/5e601cc1a4fa9be79c75fa39db4086d6ac8def4a/cypress/utils/commands.js#L99-L106

@joshuali925 Deleting `.kibana_*` may cause Kibana unhealthy. 

I just run an experiment. Deleting `opensearch_dashboards*` shall be sufficient to re-enable the button to add sample data

**Comment by tianleh** [comment]
@junqiu-lei 

I notice there two test files are not cleaning up sample data.


https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js#LL14C20-L14C20

https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js#L14

There are two ways to fix it.

1. use UI to remove sample data.
2. call delete indices to clean up. https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/observability-dashboards/8_after.spec.js#L10

**Comment by junqiu-lei** [comment]
Hi @tianleh, checking, thanks the solution, is this a blocking for 2.6 release?

**Comment by junqiu-lei** [comment]
> @junqiu-lei I think we fixed this in our repo. Can we add it here?

Yes, I am preparing the PR

**Comment by joshuali925** [comment]
observability is already calling `cy.deleteAllIndices()` https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/22322f04cc80710022e9c665a14e99fa387547d1/cypress/integration/plugins/observability-dashboards/8_after.spec.js#L8-L11, shouldn't cause this issue for others

plugins can call API to add sample data, or use UI but make it work if data is already added to make tests more defensive
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/5e601cc1a4fa9be79c75fa39db4086d6ac8def4a/cypress/integration/plugins/reports-dashboards/01-create.spec.js#L16-L19
