### ISSUE TITLE
Integtests are executed for all components even when -t component is passed when TEST_TYPE is checked to manifest.

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/opensearch-dashboards-functional-test#648]
### Is your feature request related to a problem?
Current integtest script is executing all the components even when -t parameter is passed when osd-build-manifest file exists in the local-test-cluster [path](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/9e838bb9ba4b2c64ed2fb8337cde9e522824bab2/test_finder.sh#L5)

### To Reproduce
Execute integtest script inside ftrepo with osd-build-manifest in the path https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/9e838bb9ba4b2c64ed2fb8337cde9e522824bab2/test_finder.sh#L5

This is currently running for all components instead of the specified component to -t as manifest TEST_TYPE is checked.

### What solution would you like?
Fix PR for the issue https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/644

### Do you have any additional context?
The issue is obstructing the use of -t parameter from integtest workflow view for OpenSearch Dashboards 
Refer the [issue](https://github.com/opensearch-project/opensearch-build/pull/3316#discussion_r1173168346) to run Integtests for dashboards in parallel.

**Comment by peterzhuamazon** [comment]
@tianleh to comment on is this a good option to go ahead.

Thanks.
