### ISSUE TITLE
[FEATURE] call AD test cases inside this repo from AD's CI process

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#65]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is, e.g. _I'm always frustrated when [...]_

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by ohltyler** [comment]
Tracking in AD via https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/162

**Comment by ohltyler** [comment]
@tianleh @Tengda-He this is addressed in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/163

Please have a look when you get a chance

**Comment by tianleh** [comment]
@seraphjiang cc for visibility

**Comment by ohltyler** [comment]
Resolved in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/163
