### ISSUE TITLE
[Test Update] Table Visualization split table.

### ISSUE THREAD

**Issue by curq** [opensearch-project/opensearch-dashboards-functional-test#730]
In [this PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4272), The custom class `visTable__groupInColumns` was removed, and now it causes failure of the tests.
Specifically, this test case:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/6823c8202eb8aca8ec1ef1dee41c9e25f65622ab/cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js#L60 

The PR in question, moves the split tables direction logic from the custom css classes to `OuiFlex` components for better OUI compliance, so the `visTable__groupInColumns` will be removed by it and therefore the tests need to be updated to reflect this change.

**Comment by joshuarrrr** [comment]
completed via #731, this can be closed.

**Comment by joshuarrrr** [comment]
@dblock Can you help get someone to close this untriaged issue?
