### ISSUE TITLE
dashboards-observability

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#74]
See the main tracking issue for instructions https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/72

**Comment by tianleh** [comment]
@davidcui1225 Will you work on this issue?

**Comment by tianleh** [comment]
@davidcui1225 Shall we close this issue given the PR has merged?

**Comment by davidcui1225** [comment]
Yes, I will close this issue and cut a new one to address skipped tests
