### ISSUE TITLE
alerting-dashboards-plugin

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#75]
See the main tracking issue for instructions https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/72

**Comment by tianleh** [comment]
I think we can close this issue since https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/103 is merged. Thoughts? @leeyun-amzn

**Comment by leeyun-amzn** [comment]
There are actually more test files to be added. We can keep this issue open to track. 
The remaining files are
`acknowledge_alerts_modal_spec.js`
`alert_spec.js`
`alerts_dashboard_flyout_spec.js`
`bucket_level_monitor_spec.js`
`query_level_monitor_spec.js`
