### ISSUE TITLE
[BUG] PR #763 broke npm install on Windows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-dashboards-functional-test#769]
This broke the npm install on windows.
When 1st install it wont show any errors.
But when you try to run npm install again or run anything related to npx.
It will show this error here:

```

npm ERR! Invalid Version: ^4.1.3

```

Revert the #763 commit would restore the old behavior.

Thanks.

**Comment by SuZhou-Joe** [comment]
Fixed in #772 by using npm v8 overrides.
