### ISSUE TITLE
upgrade Cypress to a newer 6.x version

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#81]

**Comment by tianleh** [comment]
@joshuali925

**Comment by tianleh** [comment]
@peterzhuamazon After talking with Josh, seems it is feasible to use a 6.x Cypress for arm64

**Comment by peterzhuamazon** [comment]
Until AD fix issues with Cypress 6 we still need to use 5.6.
And since dashboards is on the process of upgrading node version.
I do not see a point to try out 6 at this moment.
We can straight go to 7+ once node version upgrade is complete.

Thanks.

**Comment by seraphjiang** [comment]
one strong reason we should push to separate test host and test client environment.

Functional test should only depends on its own runtime, browser, network

**Comment by tianleh** [comment]
Since we decouple the test repo and the test client repo, we are now able to manage Cypress versions without worrying about the Node version used by OSD.

@ohltyler Peter mentioned that AD tests have some dependency on 5.6.0 For the release tests moved here, is this still a dependency? If not, we can start upgrading Cypress in the FT repo. cc @peterzhuamazon @seraphjiang

**Comment by tianleh** [comment]
@ohltyler Please share your input.

**Comment by ohltyler** [comment]
@tianleh I'm ok to upgrade Cypress to 6.x - I believe there is some breaking changes that cause some AD tests to fail when upgrading, which is why Peter had to run the separate older version for our plugin. But I can prioritize fixing those during/after an upgrade to 6.x, no problem.

**Comment by peterzhuamazon** [comment]
> @tianleh I'm ok to upgrade Cypress to 6.x - I believe there is some breaking changes that cause some AD tests to fail when upgrading, which is why Peter had to run the separate older version for our plugin. But I can prioritize fixing those during/after an upgrade to 6.x, no problem.

You can even aim for cypress 8+ since node is going to be upgraded to 14.

**Comment by tianleh** [comment]
cc @ohltyler @joshuali925 I will take care of updating the existing old functions used in tests to their replacement in 9.5.2

**Comment by tianleh** [comment]
Already upgraded to `9.5.4`

https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/203
