### ISSUE TITLE
query-workbench-dashboards

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-dashboards-functional-test#82]
support query workbench cypress tests, see #72

**Comment by tianleh** [comment]
I think this issue can be closed given PR merged https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/98 unless you have more query workbench tests to onboard.

**Comment by tianleh** [comment]
@davidcui1225

**Comment by davidcui1225** [comment]
It can be closed, and I have already cut a separate issue to delete the workbench test data after tests run
