### ISSUE TITLE
[FEATURE] Support phased release of Dashboards plugins

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#84]
**Is your feature request related to a problem?**
Currently the functional tests are executed as a whole https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/integtest.sh#L89 However, Dashboards plugin releases could be phased and may not even release at all sometimes. Thus we may need a way to support this phased release of Dashboards plugins.

**What solution would you like?**
support phased release of Dashboards plugins

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by tianleh** [comment]
Thanks @kavilla for bringing this up.

**Comment by tianleh** [comment]
We could potentially have a well structured reports to indicate component level situation. Open for more ideas.

**Comment by kavilla** [comment]
Makes sense I know every distribution will get published with a `manifest` that indicates which components are in it. It could be a simple as the `integtest.sh` script opening that file and reading which components are there and executing the directories for the plugins that exist.

**Comment by tianleh** [comment]
cc @kavilla since as 2.0.0 is on the way.

**Comment by tianleh** [comment]
Implemented in https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/153 by @kavilla
