### ISSUE TITLE
[BUG] Reports dashboards flaky tests with security

### ISSUE THREAD

**Issue by kavithacm** [opensearch-project/opensearch-dashboards-functional-test#889]
PRs that skipped when security is enabled

- https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/888
- https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/894
- https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/924

Requirements

- Fix for the flaky test - Download csv from saved search in-context menu

**Comment by ruanyl** [comment]
@kavithacm Do you have any plan to fix it in the coming release?

**Comment by ps48** [comment]
@ruanyl We can close this issue. I don't see any skips in reporting downloads spec file both in [main](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress/integration/plugins/reports-dashboards/04-download.spec.js) and [2.x](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/2.x/cypress/integration/plugins/reports-dashboards/04-download.spec.js)

**Comment by ruanyl** [comment]
> @ruanyl We can close this issue. I don't see any skips in reporting downloads spec file both in [main](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress/integration/plugins/reports-dashboards/04-download.spec.js) and [2.x](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/2.x/cypress/integration/plugins/reports-dashboards/04-download.spec.js)

Thanks, closed now!
