### ISSUE TITLE
[BUG] Dashboards-Observability flaky tests 

### ISSUE THREAD

**Issue by ps48** [opensearch-project/opensearch-dashboards-functional-test#897]
### What is the bug?
Integration test for dashboards observability plugin is failing occasionally and should be made more robust. Currently below failing tests are marked as excluded in 2.10 from PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/896

### How can one reproduce the bug?
* Panels - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.10.0/6610/linux/arm64/tar/test-results/4173/integ-test/observabilityDashboards/with-security/stdout.txt
* Notebooks - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.10.0/6610/linux/x64/tar/test-results/4176/integ-test/observabilityDashboards/with-security/stdout.txt

### What is the expected behavior?
The above two tests must pass without the exclusion.

### What is your host/environment?
* OSD 2.10 

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by wanglam** [comment]
Hi @ps48, do you have any plan to fix this issue in the coming release?

**Comment by wanglam** [comment]
Hi @ps48 , just find there are two PRs to related to this issue. The #1001 has been merged, and #1006 has been approved. Shall we close this issue after all the PRs merged?

**Comment by ps48** [comment]
Yes let's merge the PR with backports and then we should be good to close here. It would be better to verify the CI for observability is green for panels and notebooks after all PRs are merged in.

**Comment by wanglam** [comment]
Hi @ps48 , It seems the observability tests workflow still [failed](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7757483050/attempts/1) in the 2.x branch. Could you help me take a look?

**Comment by ps48** [comment]
@wanglam we are good to close the issue as observability tests are green and passing. We just need some reviews for backports to main: [PR1](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1067) & [PR2](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1063)

**Comment by wanglam** [comment]
These backport PRs has been merged. Close this issue.
