### ISSUE TITLE
Add test cases for parity with manual sanity test

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#9]
Current sanity test is a manual process which contains a few steps. To reduce this effort, we want to write test cases to automate these. It involves the following sub issues:

1) https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/13
2) https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/12
3) https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/11
4) https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/10

**Comment by Tengda-He** [comment]
finished
