### ISSUE TITLE
[BUG] Filter disabled: goal and guages test is not stable

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/opensearch-dashboards-functional-test#90]
**What is the bug?**
I'm running this test and target 1.2 OpenSearchDashboard, and failed with "Expected to find content: '/^7,544$/' within the element"

The following test failed which looking for the value 7,544, but our page is 7565, and this bug comment showing below, can we make this test stable, what kind of situation about "sometimes", and how we fixes the "sometimes" situation. Thanks 

      it('Filter disabled: goal and guages', () => {
        // Goal label should be 7,544, and the gauge label should be 39.958%%
        // Inconsistency: original code says that the goal label should have "7,544",
        // but sometimes the goal displays "7,565". It may have been related to a
        // data loading issue.
        commonUI.checkValuesExistInComponent('svg > g > g > text.chart-label', [
          '7,544',
          '39.958%',
        ]);
      });

  1) dashboard filtering
       Adding and removing filters from a dashboard
         disabling a filter unfilters the data on
           Filter disabled: goal and guages:
     AssertionError: Timed out retrying: Expected to find content: '/^7,544$/' within the element: [ <text.chart-label>, 1 more... ] but never did.

**How can one reproduce the bug?**
npx cypress run --spec "cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/*.js" --env "openSearchUrl={our 1.2 endpoint}" --config "baseUrl={our1.2 endpoint}"

**What is the expected behavior?**
Filter disabled: goal and guages should pass

**What is your host/environment?**
 - OS: IOS
 - Version 12.2

**Do you have any screenshots?**
Yes
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/33105471/153228993-ad2835d8-fe2b-4728-867c-f2f9e3746de6.png">

**Do you have any additional context?**
N/A

**Comment by tianleh** [comment]
We can skip it for now https://www.tabnine.com/code/javascript/functions/jest/It/skip
