### ISSUE TITLE
Add retry for `waitForSearch()` helper function

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/opensearch-dashboards-functional-test#950]
Within the data explorer tests, `waitForSearch()` is waiting for the discover table `docTable` to finish loading. However, sometimes the doc table takes too long to load, and will cause this function to fail. 

For some of the flaky tests, we can add try and catch block for `waitForSearch()` and if it fails, try reloading the table; and if that fails again, throw an error.

**Comment by ruanyl** [comment]
Hi @abbyhu2000 could you provide a bit more details about the flaky test? like the test file name and test cases. And do you plan to fix it in the coming release?

**Comment by abbyhu2000** [comment]
@ruanyl The flaky tests are these: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5495. After discussing with team, we decided to skip those flaky tests. I think we can close this issue.

**Comment by ruanyl** [comment]
@abbyhu2000 Thanks for the update, looks like you're tracking the flaky test in OSD repo, then I'll close this issue now :)
