### ISSUE TITLE
[BUG]Flaky tests are found in `core-opensearch-dashboards/vanilla-opensearch-dashboards`

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/opensearch-dashboards-functional-test#961]
### What is the bug?
Flaky tests are found in `core-opensearch-dashboards/vanilla-opensearch-dashboards`, you can find the detail logs in https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/6976620693/job/18985307702?pr=960

### How can one reproduce the bug?
Create a PR against main and you will find Snapshot based E2E Cypress tests workflow / Run Cypress E2E tests action fails.

### What is the expected behavior?
The test case should pass.

### What is your host/environment?
Ubuntu latest, github CI environment

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/13493605/eeab8a61-ba4a-4052-93a2-2cdf4a5f6d64)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by SuZhou-Joe** [comment]
@kavilla Would you mind taking a look on this issue? The flaky vanilla-dashboard-test is annoying and we need to explain the context in every PR.

**Comment by kavilla** [comment]
> @kavilla Would you mind taking a look on this issue? The flaky vanilla-dashboard-test is annoying and we need to explain the context in every PR.

Sure. Will cc @manasvinibs . 

Honestly Im not quite sure if the whole vanilla tests need to be called out anyways. They should be the same and one problem here is that the only time these tests are getting ran is in the GitHub CI. I wonder if its worth deleting them

**Comment by kavilla** [comment]
@seraphjiang @tianleh 

Do you guys have context around these tests? I will check through them and verify if I can just move some or delete some but I will look into removing these since they don't get ran from the OSS release and within the core OSD repo CI.
